// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdedlkgysrlyrhtvtyey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkZWRsa2d5c3JseXJodHZ0eWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTY5MTUsImV4cCI6MjA2MDE5MjkxNX0.kHR_14KdxzDs6Mj6WPGw7ZvTXAmrDXNWRxc7N5fkXg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);